version: "3.9"

services:
  app:
    build: .
    container_name: bun_app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["bun", "src/index.ts"]
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.1
    container_name: bun_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s


volumes:
  db_data:
