version: "3.9"

services:
  app:
    build: .
    container_name: bun_app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db
    command: ["bun", "src/index.ts"]
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: bun_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
