name: Dependency Update Check

on:
  schedule:
    # Check for updates every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun.js
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies with Bun..."
        bun outdated || true

    - name: Security audit
      run: |
        echo "Running security audit..."
        bun audit || true

    - name: Update dependencies (dry run)
      run: |
        echo "Simulating dependency update..."
        bun update --dry-run || true

    - name: Create issue if updates available
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          try {
            const outdated = execSync('bun outdated --json', { encoding: 'utf8' });
            if (outdated.trim()) {
              const title = 'Dependency Updates Available';
              const body = `
              ## 📦 Dependency Updates Available
              
              The following dependencies have updates available:
              
              \`\`\`json
              ${outdated}
              \`\`\`
              
              Consider updating these dependencies to get the latest features and security fixes.
              
              Run \`bun update\` to update dependencies.
              `;
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['dependencies', 'maintenance']
              });
            }
          } catch (error) {
            console.log('No updates available or error checking updates');
          }
